import type { Nft } from "./types";

const featuredNfts: Nft[] = [
  {
    id: "emerald-ape-042",
    name: "Emerald Ape #042",
    tokenId: "0042",
    collection: "Kurio Apes",
    artist: "Nova Sato",
    image: "/artworks/emerald.png",
    price: "1.19",
    network: "Ethereum",
    category: "Arte digital",
    edition: 50,
    available: 8,
    rating: "4.8",
    description:
      "Um colecionável digital finalizado à mão da coleção Kurio Editions, verificado na Ethereum, com arte desbloqueável e acesso para colecionadores.",
    attributes: ["Óculos", "Esmeralda", "Raro"],
  },
  {
    id: "sage-nomad-009",
    name: "Sage Nomad #009",
    tokenId: "0009",
    collection: "Kurio Nomads",
    artist: "Luna Reis",
    image: "/artworks/sage.png",
    price: "1.69",
    network: "Polygon",
    category: "Fotografia",
    edition: 10,
    available: 4,
    rating: "4.9",
    description:
      "Uma edição limitada que celebra viagens, memória e novas paisagens da cultura digital.",
    attributes: ["Explorador", "Sálvia", "Edição limitada"],
  },
  {
    id: "neon-vessel-552",
    name: "Neon Vessel #552",
    tokenId: "0552",
    collection: "Kurio Apes",
    artist: "Davi Costa",
    image: "/artworks/neon.png",
    price: "1.99",
    network: "Ethereum",
    category: "Arte 3D",
    edition: 50,
    available: 13,
    rating: "4.7",
    description:
      "Retrato digital da série Kurio, com procedência registrada e atributos exclusivos.",
    attributes: ["Neon", "Safira", "Colecionável"],
  },
  {
    id: "cosmic-bloom-118",
    name: "Cosmic Bloom #118",
    tokenId: "0118",
    collection: "Cosmic Bloom",
    artist: "Luna Reis",
    image: "/artworks/cosmic.png",
    price: "1.29",
    network: "Solana",
    category: "Generativa",
    edition: 50,
    available: 11,
    rating: "4.6",
    description:
      "Arte generativa que combina formas orgânicas e cor em uma coleção de edições abertas.",
    attributes: ["Cósmico", "Orgânico", "Generativa"],
  },
  {
    id: "violet-nomad-314",
    name: "Violet Nomad #314",
    tokenId: "0314",
    collection: "Kurio Nomads",
    artist: "Nova Sato",
    image: "/artworks/violet.png",
    price: "1.39",
    network: "Polygon",
    category: "Fotografia",
    edition: 10,
    available: 6,
    rating: "4.9",
    description:
      "Retrato da coleção Nomads, criado para colecionadores que exploram novas culturas.",
    attributes: ["Violeta", "Nomad", "Raro"],
  },
  {
    id: "ivory-baron-088",
    name: "Ivory Baron #088",
    tokenId: "0088",
    collection: "Kurio Apes",
    artist: "Davi Costa",
    image: "/artworks/ivory.png",
    price: "1.79",
    network: "Ethereum",
    category: "Arte digital",
    edition: 10,
    available: 9,
    rating: "4.8",
    description:
      "Uma peça de edição limitada com atributos raros e registro permanente de procedência.",
    attributes: ["Marfim", "Alfaiataria", "Raro"],
  },
  {
    id: "golden-beat-207",
    name: "Golden Beat #207",
    tokenId: "0207",
    collection: "Golden Signals",
    artist: "Luna Reis",
    image: "/artworks/golden-beat.png",
    price: "0.99",
    network: "Solana",
    category: "Música",
    edition: 50,
    available: 19,
    rating: "4.5",
    description:
      "Uma homenagem visual à música e às comunidades que criam cultura na internet.",
    attributes: ["Música", "Ouro", "Edição aberta"],
  },
  {
    id: "golden-signal-160",
    name: "Golden Signal #160",
    tokenId: "0160",
    collection: "Golden Signals",
    artist: "Nova Sato",
    image: "/artworks/golden-signal.png",
    price: "0.39",
    network: "Solana",
    category: "Utilidade",
    edition: 50,
    available: 23,
    rating: "4.7",
    description:
      "Acesso digital para colecionadores e apoiadores das próximas edições da comunidade.",
    attributes: ["Sinal", "Ouro", "Utilidade"],
  },
  {
    id: "quiet-garden-721",
    name: "Quiet Garden #721",
    tokenId: "0721",
    collection: "Quiet Gardens",
    artist: "Marco Silva",
    image: "/artworks/cosmic.png",
    price: "0.82",
    network: "Polygon",
    category: "Generativa",
    edition: 50,
    available: 16,
    rating: "4.6",
    description:
      "Composição generativa inspirada em jardins urbanos e espaços de contemplação.",
    attributes: ["Jardim", "Sereno", "Generativa"],
  },
  {
    id: "ivory-study-014",
    name: "Ivory Study #014",
    tokenId: "0014",
    collection: "Kurio Studies",
    artist: "Davi Costa",
    image: "/artworks/ivory.png",
    price: "2.29",
    network: "Ethereum",
    category: "Arte 3D",
    edition: 10,
    available: 2,
    rating: "4.9",
    description:
      "Estudo digital em edição curta, com procedência e direitos autorais documentados.",
    attributes: ["Estudo", "Marfim", "Edição curta"],
  },
  {
    id: "violet-signal-031",
    name: "Violet Signal #031",
    tokenId: "0031",
    collection: "Golden Signals",
    artist: "Nova Sato",
    image: "/artworks/violet.png",
    price: "0.72",
    network: "Solana",
    category: "Música",
    edition: 50,
    available: 18,
    rating: "4.5",
    description:
      "Peça digital inspirada nos sinais visuais da música independente.",
    attributes: ["Violeta", "Música", "Sinal"],
  },
  {
    id: "nomad-edition-101",
    name: "Nomad Edition #101",
    tokenId: "0101",
    collection: "Kurio Nomads",
    artist: "Luna Reis",
    image: "/artworks/sage.png",
    price: "1.05",
    network: "Polygon",
    category: "Fotografia",
    edition: 50,
    available: 7,
    rating: "4.7",
    description:
      "Uma edição para colecionadores que valorizam histórias e novas perspectivas.",
    attributes: ["Nomad", "Viagem", "Colecionável"],
  },
];

export const nfts: Nft[] = [
  ...featuredNfts,
  ...[1, 2].flatMap((series) =>
    featuredNfts.map((nft) => {
      const tokenId = String(Number(nft.tokenId) + series * 1000).padStart(4, "0");
      return {
        ...nft,
        id: `${nft.id}-${series}`,
        name: nft.name.replace(/#\d+$/, `#${tokenId}`),
        tokenId,
        price: (Number(nft.price) + series * 0.2).toFixed(2),
        available: Math.max(nft.available - series, 1),
        description: `${nft.description} Edição ${series}.`,
      };
    }),
  ),
];

export const categories = [
  "Arte digital",
  "Fotografia",
  "Música",
  "Arte 3D",
  "Colecionáveis",
  "Generativa",
  "Jogos",
  "Assinaturas",
  "Utilidade",
];
